name: IPCA Pipeline

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 15,28 * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS creds loaded"

      - name: Run ingestion
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          python ingest_ipea_to_s3.py

      - name: Init duckdb
        run: |
          python scripts/init_duckdb.py
      
      - name: Load raw to duckdb
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1
        run: |
          python scripts/load_ipca_to_duck.py

      - name: Run dbt stg and int
        env:
          DBT_PROFILES_DIR: .
        run: |
          cd dbt_ipea
          dbt deps
          dbt run --select staging
          dbt run --select intermediate
          dbt test --select staging
          dbt test --select intermediate

      - name: Run forecast
        run: |
          python pipelines/forecast.py

      - name: Run dbt marts
        env:
          DBT_PROFILES_DIR: .
        run: |
          cd dbt_ipea
          dbt deps
          dbt run --select marts
          dbt test --select marts

      - name: Commit updated DuckDB
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/duckdb/ipea.duckdb
          git commit -m "Update DuckDB - $(date -u)" || echo "No changes"
          git push